# Default initial positions for xarm's ros2_control fake system

initial_positions:
  base_to_link1: 0
  gripper_finger1_joint: 0
  gripper_finger2_joint: 0
  link1_to_link2: 0
  link2_to_link3: 0
  link5_to_gripperbase: 0
  linkt_to_link5: 0